---
os: linux
arch:
 - amd64
 - ppc64le
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - rm .travis.yml
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm --with-recommends --installdeps -n .
language: perl
perl:
  - '5.22'
  - '5.24'
  - '5.26'
  - '5.28'
  - '5.30'
script:
  - prove -l t
